baseURL = "https://yoli.care"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS"]
enableRobotsTXT = true
defaultContentLanguage = "en"
theme = "hugo-scroll"
title = "Yoli - Autism care that cares"

# enable emoji processing in Markdown (valid only for pure markdown content)
enableEmoji = true

# Override default publishing (/public) path
publishDir = "docs"

[[menu.main]]
    pre = "Now Accepting New Client:"
    name = "Start here"
    url = "https://forms.gle/EFY2tqJVWx2terSu5"
    weight = 1

[[menu.main]]
    name = "Support our mission"
    url = "/donate"
    post = '<i class="fa-solid fa-star"></i>'
    weight = 2

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/yoli-preview.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Yoli - Autism care that cares"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Yoli offers neurodiversity-affirming, play-based ABA therapy in Albany, CA. A nonprofit serving Berkeley, El Cerrito, and the East Bay with a child-led focus."

    # Show a menu of languages available
    language_menu = false

    # Show also a language menu item for the current language, if false only
    # show the remaining languages
    show_current_lang = false

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "&copy; {year} - Yoli"

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false
    
    # Options used for automatic image generation. see: https://gohugo.io/content-management/image-processing/
    image_options = "webp q90 lanczos photo"
    
    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = true

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = true

    [params.meta]
        keywords = "Neurodiversity affirming ABA, Play-based therapy Albany CA, Autism support East Bay, Nonprofit ABA Berkeley, Yoli autism care"

    [[params.contacts]]
        label = "phone"
        value = "(510) 679-2782 (call or text)"
        url = "tel:+1 510 679-2782"
        icon = "fa fa-phone"

    [[params.contacts]]
        label = "fax"
        value = "(510) 905-0712"
        icon = "fa fa-fax"

    [[params.contacts]]
        label = "email"
        value = "email (form)"
        url = "https://forms.gle/EFY2tqJVWx2terSu5"
        icon = "fa fa-envelope"

    [[params.contacts]]
        label = "address"
        value = "1057 Solano Ave, Ste 104 <br/> Albany, CA 94706 United States"
        url = "http://maps.google.com/?q=Yoli 1057 Solano Ave, Albany, CA 94706 United States"
        icon = "fa fa-location-dot"
